# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Seong-eun Cho
tagline:          ''
description:      |
                  <p>Cognitive Neuroscience Researcher</p>
                  <p>ðŸ”¬ Research Interests: Spatial Cognition, Episodic Memory</p>
                  <p>ðŸ’Œ Contact: chosee@snu.ac.kr</p>
url:              https://chosenne96.github.io
baseurl:          /

author:
  name:           'Seong-eun Cho'
  url:            https://chosenne96.github.io

paginate:         5

plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chosenne96
